### ISSUE TITLE
Keyboard profile switching blacks out GameSense keys until they are updated

### ISSUE THREAD

**Issue by vinnydiehl** [JayJay1989/GameSenseSDK#10]
When used in conjunction with SteelSeries Engine profile switching, the GameSense-controlled keys go black until they are updated. The compass obviously begins to work again immediately, and the tool durability may be reset quickly by scrolling through your hotbar, but the hunger and health bars may take quite some time to see a change. Suggest updating all of the elements whenever the window is brought into focus, perhaps with a slight delay to give the profile switcher a chance to kick in?

**To Reproduce**

1. Link a custom keyboard profile to the javaw that your Minecraft uses.
2. Set the keyboard to a default profile with no executable linked to it.
3. Launch Minecraft and begin playing without clicking away. The keyboard profile will switch over, and the GameSense keys will work as expected.
4. Alt-Tab away. The profile will switch back to the default. The GameSense keys will go black, this appears to be a SteelSeries Engine bug.
5. Alt-Tab back to Minecraft. The profile will switch to your Minecraft profile, and the GameSense keys will remain black until updated by the mod.
6. Exit Minecraft. The keys will remain black until the Minecraft GameSense app is turned off and back on in the Engine! This is absolutely SteelSeries' problem and there is nothing you can do about it- in fact, this entire bug is a SteelSeries issue that you have to work around. If you have a contact with them you may wish to report this behavior.

**Expected Behavior**

Upon bringing Minecraft back into focus, the GameSense keys update and begin to display data immediately.

**Minecraft Enviroment**
 - OS: Windows 10 Home Update 1809
 - Ram allocated: 20G
 - Minecraft & Forge version: 1.15.2 - 31.1.63
 - Mod Version: 1.15.2

**Additional Context**
I realize that this issue largely isn't your fault, but this is a common use case and something I thought you should be aware of. Cheers!

**Comment by JayJay1989** [comment]
This is a Steelseries gamesense program problem. Can't fix this issue
