### ISSUE TITLE
Mod can not be loaded server side

### ISSUE THREAD

**Issue by Isfirs** [JayJay1989/GameSenseSDK#5]
**Describe the bug**
GameSense can not be started on the server side due to a missing dependency.

**To Reproduce**
1. Setup forge Server
2. Install Mod in Server
3. Start Server

**Logs/crashlogs/etc**
https://gist.github.com/Isfirs/556f0961e0fc0cca4e3b9f712d1c1300

**Expected behavior**
Server should ignore Client only mod

**Screenshots**
-

**Minecraft enviroment:**
 - OS: Windows 10
 - Ram allocated: VM default
 - Minecraft & Forge version: 1.12.2-14.23.5.2836
 - Mod Version 1.12.9

**Additional context**
-

**Comment by JayJay1989** [comment]
Gamesense is a client only mod. dont use it on a server...

**Comment by Isfirs** [comment]
If that is the reaction to it, so be it:
Please add the capability to detect that the mod is client side only as "normal" mods to. Ty. Removes some confusion. Thought that was obvious.

Sincerely Isfirs

**Comment by JayJay1989** [comment]
nope, everyone using this mod knows it. Its on the mod page...

**Comment by JayJay1989** [comment]
this mods adds nothing to the server. So why trying to add it?
